/*
.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// QvmListerExpansion allows custom methods to be added to
// QvmLister.
type QvmListerExpansion interface{}

// QvmNamespaceListerExpansion allows custom methods to be added to
// QvmNamespaceLister.
type QvmNamespaceListerExpansion interface{}
