/*
.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "qiniu.com/qvirt/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Qvms returns a QvmInformer.
	Qvms() QvmInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Qvms returns a QvmInformer.
func (v *version) Qvms() QvmInformer {
	return &qvmInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
