/*
.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	qvmv1alpha1 "qiniu.com/qvirt/apis/qvm/v1alpha1"
	internalinterfaces "qiniu.com/qvirt/client/informers/externalversions/internalinterfaces"
	v1alpha1 "qiniu.com/qvirt/client/listers/qvm/v1alpha1"
	versioned "qiniu.com/qvirt/client/versioned"
)

// QvmInformer provides access to a shared informer and lister for
// Qvms.
type QvmInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.QvmLister
}

type qvmInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewQvmInformer constructs a new informer for Qvm type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewQvmInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredQvmInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredQvmInformer constructs a new informer for Qvm type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredQvmInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QvmV1alpha1().Qvms(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.QvmV1alpha1().Qvms(namespace).Watch(context.TODO(), options)
			},
		},
		&qvmv1alpha1.Qvm{},
		resyncPeriod,
		indexers,
	)
}

func (f *qvmInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredQvmInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *qvmInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&qvmv1alpha1.Qvm{}, f.defaultInformer)
}

func (f *qvmInformer) Lister() v1alpha1.QvmLister {
	return v1alpha1.NewQvmLister(f.Informer().GetIndexer())
}
