/*
.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "qiniu.com/qvirt/apis/qvm/v1alpha1"
	scheme "qiniu.com/qvirt/client/versioned/scheme"
)

// QvmsGetter has a method to return a QvmInterface.
// A group's client should implement this interface.
type QvmsGetter interface {
	Qvms(namespace string) QvmInterface
}

// QvmInterface has methods to work with Qvm resources.
type QvmInterface interface {
	Create(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.CreateOptions) (*v1alpha1.Qvm, error)
	Update(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.UpdateOptions) (*v1alpha1.Qvm, error)
	UpdateStatus(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.UpdateOptions) (*v1alpha1.Qvm, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Qvm, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.QvmList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Qvm, err error)
	QvmExpansion
}

// qvms implements QvmInterface
type qvms struct {
	client rest.Interface
	ns     string
}

// newQvms returns a Qvms
func newQvms(c *QvmV1alpha1Client, namespace string) *qvms {
	return &qvms{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the qvm, and returns the corresponding qvm object, and an error if there is any.
func (c *qvms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Qvm, err error) {
	result = &v1alpha1.Qvm{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("qvms").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Qvms that match those selectors.
func (c *qvms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QvmList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.QvmList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("qvms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested qvms.
func (c *qvms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("qvms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a qvm and creates it.  Returns the server's representation of the qvm, and an error, if there is any.
func (c *qvms) Create(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.CreateOptions) (result *v1alpha1.Qvm, err error) {
	result = &v1alpha1.Qvm{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("qvms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(qvm).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a qvm and updates it. Returns the server's representation of the qvm, and an error, if there is any.
func (c *qvms) Update(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.UpdateOptions) (result *v1alpha1.Qvm, err error) {
	result = &v1alpha1.Qvm{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("qvms").
		Name(qvm.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(qvm).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *qvms) UpdateStatus(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.UpdateOptions) (result *v1alpha1.Qvm, err error) {
	result = &v1alpha1.Qvm{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("qvms").
		Name(qvm.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(qvm).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the qvm and deletes it. Returns an error if one occurs.
func (c *qvms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("qvms").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *qvms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("qvms").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched qvm.
func (c *qvms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Qvm, err error) {
	result = &v1alpha1.Qvm{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("qvms").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
