/*
.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "qiniu.com/qvirt/client/versioned/typed/qvm/v1alpha1"
)

type FakeQvmV1alpha1 struct {
	*testing.Fake
}

func (c *FakeQvmV1alpha1) Qvms(namespace string) v1alpha1.QvmInterface {
	return &FakeQvms{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeQvmV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
