/*
.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "qiniu.com/qvirt/apis/qvm/v1alpha1"
)

// FakeQvms implements QvmInterface
type FakeQvms struct {
	Fake *FakeQvmV1alpha1
	ns   string
}

var qvmsResource = schema.GroupVersionResource{Group: "qvm", Version: "v1alpha1", Resource: "qvms"}

var qvmsKind = schema.GroupVersionKind{Group: "qvm", Version: "v1alpha1", Kind: "Qvm"}

// Get takes name of the qvm, and returns the corresponding qvm object, and an error if there is any.
func (c *FakeQvms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Qvm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(qvmsResource, c.ns, name), &v1alpha1.Qvm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Qvm), err
}

// List takes label and field selectors, and returns the list of Qvms that match those selectors.
func (c *FakeQvms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QvmList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(qvmsResource, qvmsKind, c.ns, opts), &v1alpha1.QvmList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.QvmList{ListMeta: obj.(*v1alpha1.QvmList).ListMeta}
	for _, item := range obj.(*v1alpha1.QvmList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested qvms.
func (c *FakeQvms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(qvmsResource, c.ns, opts))

}

// Create takes the representation of a qvm and creates it.  Returns the server's representation of the qvm, and an error, if there is any.
func (c *FakeQvms) Create(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.CreateOptions) (result *v1alpha1.Qvm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(qvmsResource, c.ns, qvm), &v1alpha1.Qvm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Qvm), err
}

// Update takes the representation of a qvm and updates it. Returns the server's representation of the qvm, and an error, if there is any.
func (c *FakeQvms) Update(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.UpdateOptions) (result *v1alpha1.Qvm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(qvmsResource, c.ns, qvm), &v1alpha1.Qvm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Qvm), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeQvms) UpdateStatus(ctx context.Context, qvm *v1alpha1.Qvm, opts v1.UpdateOptions) (*v1alpha1.Qvm, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(qvmsResource, "status", c.ns, qvm), &v1alpha1.Qvm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Qvm), err
}

// Delete takes name of the qvm and deletes it. Returns an error if one occurs.
func (c *FakeQvms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(qvmsResource, c.ns, name), &v1alpha1.Qvm{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeQvms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(qvmsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.QvmList{})
	return err
}

// Patch applies the patch and returns the patched qvm.
func (c *FakeQvms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Qvm, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(qvmsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Qvm{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Qvm), err
}
